sudo: required
services:
  - docker

before_install:
  - docker build -t anggadarkprince/react-app -f ./client/Dockerfile.dev ./client

script:
  - docker run anggadarkprince/react-app npm run test -- --coverage

after_success:
  - docker build anggadarkrprince/multi-client ./client
  - docker build anggadarkrprince/multi-nginx ./nginx
  - docker build anggadarkrprince/multi-server ./server
  - docker build anggadarkrprince/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push anggadarkrprince/multi-client ./client
  - docker push anggadarkrprince/multi-nginx ./nginx
  - docker push anggadarkrprince/multi-server ./server
  - docker push anggadarkrprince/multi-worker ./worker